# Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [2]:
import numpy as np

In [83]:
N = 10

x = np.arange(N)[::-1] #[::-1] — 

x

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

# Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [88]:
N = 10

x = np.diag(np.arange(N)[::-1])

sum_ = np.trace(x)

sum_

45

# Задание 3
Решите систему уравнений:

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3

In [12]:
a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]]) # левая часть 
b = np.array([4, 12, -3]) # правая часть 

from numpy import linalg

np.linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [13]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

# Задание 4 
Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем.
На сайт заходит очередной посетитель. Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats


In [14]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [17]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

array([0, 1, 2, 0, 0, 0])

In [36]:
list_ = []

for i in users_stats:
    list_.append(np.dot(next_user_stats, i) / (np.linalg.norm(next_user_stats) * np.linalg.norm(i)))
    
print('Новый посетитель больше всего похож на пользователя с ID:',(list_.index(max(list_)) + 1))


Новый посетитель больше всего похож на пользователя с ID: 8
